### ISSUE TITLE
Adding org.iets3.core.expr.simpleTypes as language dependency requires reloading classes

### ISSUE THREAD

**Issue by JoostvanPinxten** [IETS3/iets3.opensource#329]
For some reason, when we add org.iets3.core.expr.simpleTypes we sometimes cannot add number literals or type information.

Reloading the classes (or invalidating the caches and restarting) fixes this problem, and it works as expected.

**Comment by fvollmer** [comment]
I also noticed, that sometimes the simpleTypes won't work until a restart. Could this be related to#315? I mean Jetbrains recommands to not cache the objects of the extension.

**Comment by wsafonov** [comment]
Could you provide a small reproducible example where it doesn't work as expected? That would make it much easier to locate the source of the problem. Otherwise if just restarting fixes the issue, it doesn't makes sense investing time into it (might be also an MPS bug), as adding simpleTypes doesn't happen on a daily basis and in general we don't experience this specific issue in other projects.

**Comment by JoostvanPinxten** [comment]
The reproducible example that I just figured out (in MPS 2019.2.4) is the following:

- create a new solution, 
- create a new model, 
- import org.iets3.core.expr.toplevel (only!)
- create a new Library, 
- create a val instance in that library
- only THEN import the org.iets3.core.expr.simpleTypes languages.

This will consistently not allow me to create number literals.

However, when I add them immediately (together with the toplevel language) then it DOES work. Invalidating caches/reloading classes does not always seem to work... So the only workaround seems to be to import toplevel and simpletypes immediately into a model...

**Comment by JoostvanPinxten** [comment]
@wsafonov can you please have a look?

**Comment by wsafonov** [comment]
@JoostvanPinxten this is probably an issue with some cache in grammar cells or in MPS, or in both. For me, an MPS restart seems to solve the issue. But even if not, I would rather say that instead of adding single languages to the model the recommended way should be using a suitable devkit instead, for example `org.iets3.core.expr.core.devkit` as the initial devkit to start from. This way you get the basic set of required languages straightaway and benefit from the devkit being maintenaned and extended by new languages as they are added to the framework.

**Comment by JoostvanPinxten** [comment]
@wsafonov Well... that seems like a workaround, and I think the majority of our users does not want to know about any of the details. Is there a way to put a dependency on the devkit, so that they are loaded immediately when our DSL using KernelF is imported?

**Comment by wsafonov** [comment]
@JoostvanPinxten ideally final tool users should not at all be confronted with all single languages required for their work and should not know which language when they need to import. Devkits provide a convenient way to hide all language packaging details from the final users and give them a single bundle that they need to import which could cover a broad area of use cases. So the recommended way would be that you define your own devkit for your domain languages (or a few of them) and import all required framework devkits like the one I mentioned before. Users should then only import devkits from your domain instead of single languages. This would again give the already mentioned advantage that you could extend the devkits with new languages created in the later tool versions and then the existing user models would automatically use those languages.

**Comment by JoostvanPinxten** [comment]
https://github.com/IETS3/iets3.core/issues/790 would be a solution at least to use 'pure' variability.

**Comment by dbinkele** [comment]
@JoostvanPinxten Is this ticket closeable?

**Comment by JoostvanPinxten** [comment]
Yes, this fixxes the issue.
