### ISSUE TITLE
Add instructions: HOWTO benefit from the tests as a documentation resource

### ISSUE THREAD

**Issue by jennek** [IETS3/iets3.opensource#330]
The KernelF tests in the tests folder are a very valuable complement to the KernelF documentation. However, it is not trivial how to incorporate them in your project. I tried this:
1) I cloned the GitHub repo and tried to build it -- build failed. Could not make it work in reasoable time.
2)  I cloned again and tried to open the .mps project within. No modules showed up in the project view - even after setting path variable ${iets3.github.opensource.home} properly. 
3)  I just copied over the test folder to another project and included the test solution .msd files in the project paths. This worked. After setting the Project Path in each of the TestInfo nodes I was able to run all tests without further ado. Yes, I know this is risky in terms of nodeIDs clashing.

I propose to work out
- instructions on ways to get access to the tests, either read-only or in runnable form
- complimentary scripts (for example: visit all TestInfo nodes and set Project Path to you local value)

**Comment by jennek** [comment]
For me, distribution in read-only mode is OK provided that the project path in the TestInfo nodes contains only a path variable. Right now it does not: in every test model it is `${iets3.github.opensource.home}/code/languages/org.iets3.opensource`. If it were only the path variable, I would have set it to the root of my project. This way you might solve it from your end.

When I would want to tweak an example and try out a few ideas, I would copy over the example anyway, in order to preserve the original. So it does not hurt that the example is read-only, it is actually helpful. (edited)

**Comment by wsafonov** [comment]
Hi @jennek,
can you provide more details on your local build problem? What kind of error did you see there? Usually, if you check out a stable version from master, you should not experience any problems with the build. The only known issue occurs on Windows systems due to the command line length limitation. If you are on Windows and you saw something like `Process fork failed` in the build, most probably you faced exactly this problem. Right now there is nothing you can do about it other than just skip running tests in the build (`gradlew buildLanguages` only builds the languages).

Setting `iets3.github.opensource.home` path variable is actually really required for being able to work with the project. You should do it before opening the project. Unfortunately we haven't properly documented this in README - I will fix this.

After setting the path variable and opening the project you should be able to see all modules of the project and run CI tests. Currently we don't provide a simple way to run all relevant project CI tests inside MPS, as we primarily rely on test execution in the command-line build (also because some tests are not intended to run in the CI build). So you would need to navigate to the tests you are interested in and manually run them from the context menu (either on module, on model or on a single test suite).

I'm not quite sure I understand what do you mean by read-only access to the tests. If you just open the iets3.opensource project, nothing should be read-only. It can be only the case if you try to open iets3.opensource project together with another MPS project you are working on that actually already has iets3.opensource as binary dependency. This is however depending on what exactly you are trying to achieve not always recommended, as it may result in mixing up incompatible versions of iets3 modules. So I would first like to understand what is your work scenario and what exactly do you need there.

**Comment by jennek** [comment]
@wsafonov thanks for picking up this issue. FYI: the text I used at the start of this issue is copy/paste from a private discussion I had with Kolja Dummann on the issue. There may be bits of context missing.

Regarding the build problem: indeed it is `Process fork failed` in "Task :buildAndRunTests ". I understand I have to live with it. No problem.

Regarding the path variable: I am trying again now -- running `gradlew buildLanguages` is taking some time -- I will report later. it is not the core issue. 

Regarding read-only: this is in the context of our internal MPS distribution as created by itemis. This distro has MPS plus mbeddr, iets3.opensource, etcetera bundled as plug-ins. I have access to thies plug-ins through the modules pool. Being a plug-in makes them read-only for me. This is not a bad thing in itself. However, the iets3.opensource plug-in does not include the tests -- which _is_ a bad thing because I think the tests are indispensable as documentation. Now suppose itemis would include the iets3.opensource tests in the distro (I asked them to), then the tests would be read-only as well. Still not a bad thing if I just want to read them. However, when I want to actually run the tests, then I need to change the project path in the TestInfo node -- which cannot be done as they are read-only. As I understand this is why itemis is hesitant to include the tests in the plug-in.

So the problem I would like to have solved is: include the tests in the internal distro in such a way that I can run them. (I assume this applies to other customers of itemis as well, but I have no info on that).

It is in this context of an internal distribution with iets3.opensource pre-loaded that I wrote the proposal.

**Comment by wsafonov** [comment]
Regarding the process fork problem, I have good news for you - I have managed to find a good workaround to solve this problem and it's already merged into master. So now running the full build on Windows including the tests should not be an issue anymore.

As for the tests, I understood that you want to include them into your distribution. You must keep in mind that executing such tests from a binary distribution using MPS UI is not supported and you won't be able to do it. I'm not familiar with the internals of the tests workbench framework at this place, but I guess that this scenario simply never was considered as tests are supposed to run only within a source distribution. That's why trying to exchage TestInfo path in such case is also not a good idea.

Still you may want to have the tests in the distribution for other reasons, for example to have them as an additional library of the language usage examples. We currently don't supply a dedicated plugin with all the tests, but you can easily create one for your distribution if you use MPS build models to package it. You would need to add `org.iets3.opensource.tests` script as a dependency and point artifacts location to the unpacked `org.iets3.opensource:tests` package from our Nexus server and import all the contents to your plugin in the build layout - this would be just couple of additions to your existing build model. Then include that new plugin to your distribution and your're done.

Btw, even if executing tests using MPS UI would not be possible, at least for the IETS3 TestSuites and TestCases, a possibility should be still there to run them and see status feedback in the read-only editor - using Ctrl+Alt+Enter shortcut. However, we have never needed that and so one have first to try it out.

**Comment by alexanderpann** [comment]
Closing because there were are no open questions anymore.
