### ISSUE TITLE
Math expressions do not work with units

### ISSUE THREAD

**Issue by bkolb** [IETS3/iets3.opensource#333]
<img width="154" alt="image" src="https://user-images.githubusercontent.com/355333/75176333-3eb22680-5734-11ea-91f2-755649f95a5f.png">

Here is an example. The result of sqrt is hard coded to be real.

**Comment by MLanghammer** [comment]
I fixed the calculation for sqrt-expressions. Example:
![grafik](https://user-images.githubusercontent.com/5717036/75696994-c1932e00-5cac-11ea-9313-cf5e48956d70.png)
Changes are currently on branch "bugfix/unit-types-for-math-expressions". 
Next, I will fix it for the remaining math-expressions and then create a PR.

**Comment by MLanghammer** [comment]
The PR should fix the issue. 

Since, we are now relaying on the inner type of the SqrtExpression, we need to to make sure that all expressions used within the SqrtExprssion have a type, i.e., in your example above "foo" needs to have a type. Otherwise the type-calculation for the whole SqrtExpression will not succeed.

**Comment by MLanghammer** [comment]
The issue should be fixed with merging PR #342
