### ISSUE TITLE
Don't generate unneccessary Closures (KernelF) 

### ISSUE THREAD

**Issue by lhartl** [IETS3/iets3.opensource#421]
In the kernelF Java generator, closures are generated for Block/If Expressions that are not always necessary. Refactor this by Identifying the cases where it is not neccessary and remove the Closures.

**Comment by jonaskraemer** [comment]
I'm don't think I understand exactly what you're suggesting here.
Do you propose to use the ternary operator instead of invoking an anonymous function?
I.e. `b ? x : y` instead of `{ => if b then x else c}.invoke()`? 

Can you clarify?

Also, can you explain what we hope to achieve with this change?

**Comment by alexanderpann** [comment]
BaseLanguage closures are nowadays compiled to Java lambdas using functional interfaces. I also don't see a reason to change this. Let's reopen the issue if there is really a need for such an optimization.
