### ISSUE TITLE
Represent State and change over time in KernelF

### ISSUE THREAD

**Issue by markusvoelter** [IETS3/iets3.opensource#68]

**Comment by alexanderpann** [comment]
Closing because I think everything now exists in KernelF: We have the virtual package lang-stateful with languages related to state and `org.iets3.core.expr.temporal` for values that change over time. On a unrelated node, there is a language for [node versioning ](https://jetbrains.github.io/MPS-extensions/extensions/node-versioning/)in mps-extensions.
